P8105\_HW\#6\_qx2199
================
Qianhui Xu
12/06/2020

``` r
library(tidyverse)
library(modelr)
library(p8105.datasets)
```

### Problem 1

``` r
homicide_df = 
  read_csv("./homicide-data.csv", na = c("", "NA", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    victim_age = as.numeric(victim_age),
    resolution = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest"        ~ 0,
      disposition == "Closed by arrest"      ~ 1)
  ) %>% 
  filter(
    victim_race %in% c("White", "Black"),
    city_state != "Tulsa, AL") %>% 
  select(city_state, resolution, victim_age, victim_race, victim_sex)
```

    ## Parsed with column specification:
    ## cols(
    ##   uid = col_character(),
    ##   reported_date = col_double(),
    ##   victim_last = col_character(),
    ##   victim_first = col_character(),
    ##   victim_race = col_character(),
    ##   victim_age = col_double(),
    ##   victim_sex = col_character(),
    ##   city = col_character(),
    ##   state = col_character(),
    ##   lat = col_double(),
    ##   lon = col_double(),
    ##   disposition = col_character()
    ## )

Start with one city.

``` r
baltimore_df =
  homicide_df %>% 
  filter(city_state == "Baltimore, MD")
glm(resolution ~ victim_age + victim_race + victim_sex, 
    data = baltimore_df,
    family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, OR, starts_with("CI")) %>% 
  knitr::kable(digits = 3)
```

| term              |    OR | CI\_lower | CI\_upper |
| :---------------- | ----: | --------: | --------: |
| (Intercept)       | 1.363 |     0.975 |     1.907 |
| victim\_age       | 0.993 |     0.987 |     1.000 |
| victim\_raceWhite | 2.320 |     1.648 |     3.268 |
| victim\_sexMale   | 0.426 |     0.325 |     0.558 |

Try this across cities.

``` r
models_results_df = 
  homicide_df %>% 
  nest(data = -city_state) %>% 
  mutate(
    models = 
      map(.x = data, ~glm(resolution ~ victim_age + victim_race + victim_sex, data = .x, family = binomial())),
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state, results) %>% 
  unnest(results) %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("CI")) 
```

``` r
models_results_df %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

<img src="p8105_hw6_qx2199_files/figure-gfm/unnamed-chunk-4-1.png" width="90%" />

## Problem 2

``` r
baby_df = read_csv("./birthweight.csv") %>% 
 janitor::clean_names() %>% 
  mutate(
    babysex = case_when(
      babysex == "1" ~ "male",
      babysex == "2" ~ "female",
      TRUE ~ as.character(babysex)
    ),
    frace = case_when(
      frace == "1" ~ "white",
      frace == "2" ~ "black",
      frace == "3" ~ "Asian",
      frace == "4" ~ "Puerto Rican",
      frace == "8" ~ "Other",
      frace == "9" ~ "Unknown",
      TRUE ~ as.character(frace)
    ),
     mrace = case_when(
      mrace == "1" ~ "white",
      mrace == "2" ~ "black",
      mrace == "3" ~ "Asian",
      mrace == "4" ~ "Puerto Rican",
      mrace == "8" ~ "Other",
      mrace == "9" ~ "Unknown",
      TRUE ~ as.character(mrace)
      ),
    malform = case_when(
      malform == "0" ~ "absent",
      malform == "1" ~ "present",
      TRUE ~ as.character(malform)
       ))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
baby_df %>% 
  mutate(
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    mrace = as.factor(mrace),
    malform = as.factor(malform)
    
  )
```

    ## # A tibble: 4,342 x 20
    ##    babysex bhead blength   bwt delwt fincome frace gaweeks malform menarche
    ##    <fct>   <dbl>   <dbl> <dbl> <dbl>   <dbl> <fct>   <dbl> <fct>      <dbl>
    ##  1 female     34      51  3629   177      35 white    39.9 absent        13
    ##  2 male       34      48  3062   156      65 black    25.9 absent        14
    ##  3 female     36      50  3345   148      85 white    39.9 absent        12
    ##  4 male       34      52  3062   157      55 white    40   absent        14
    ##  5 female     34      52  3374   156       5 white    41.6 absent        13
    ##  6 male       33      52  3374   129      55 white    40.7 absent        12
    ##  7 female     33      46  2523   126      96 black    40.3 absent        14
    ##  8 female     33      49  2778   140       5 white    37.4 absent        12
    ##  9 male       36      52  3515   146      85 white    40.3 absent        11
    ## 10 male       33      50  3459   169      75 black    40.7 absent        12
    ## # … with 4,332 more rows, and 10 more variables: mheight <dbl>, momage <dbl>,
    ## #   mrace <fct>, parity <dbl>, pnumlbw <dbl>, pnumsga <dbl>, ppbmi <dbl>,
    ## #   ppwt <dbl>, smoken <dbl>, wtgain <dbl>

``` r
baby_df %>% 
  anyNA()
```

    ## [1] FALSE

``` r
summary(baby_df)
```

    ##    babysex              bhead          blength           bwt      
    ##  Length:4342        Min.   :21.00   Min.   :20.00   Min.   : 595  
    ##  Class :character   1st Qu.:33.00   1st Qu.:48.00   1st Qu.:2807  
    ##  Mode  :character   Median :34.00   Median :50.00   Median :3132  
    ##                     Mean   :33.65   Mean   :49.75   Mean   :3114  
    ##                     3rd Qu.:35.00   3rd Qu.:51.00   3rd Qu.:3459  
    ##                     Max.   :41.00   Max.   :63.00   Max.   :4791  
    ##      delwt          fincome         frace              gaweeks     
    ##  Min.   : 86.0   Min.   : 0.00   Length:4342        Min.   :17.70  
    ##  1st Qu.:131.0   1st Qu.:25.00   Class :character   1st Qu.:38.30  
    ##  Median :143.0   Median :35.00   Mode  :character   Median :39.90  
    ##  Mean   :145.6   Mean   :44.11                      Mean   :39.43  
    ##  3rd Qu.:157.0   3rd Qu.:65.00                      3rd Qu.:41.10  
    ##  Max.   :334.0   Max.   :96.00                      Max.   :51.30  
    ##    malform             menarche        mheight          momage    
    ##  Length:4342        Min.   : 0.00   Min.   :48.00   Min.   :12.0  
    ##  Class :character   1st Qu.:12.00   1st Qu.:62.00   1st Qu.:18.0  
    ##  Mode  :character   Median :12.00   Median :63.00   Median :20.0  
    ##                     Mean   :12.51   Mean   :63.49   Mean   :20.3  
    ##                     3rd Qu.:13.00   3rd Qu.:65.00   3rd Qu.:22.0  
    ##                     Max.   :19.00   Max.   :77.00   Max.   :44.0  
    ##     mrace               parity            pnumlbw     pnumsga      ppbmi      
    ##  Length:4342        Min.   :0.000000   Min.   :0   Min.   :0   Min.   :13.07  
    ##  Class :character   1st Qu.:0.000000   1st Qu.:0   1st Qu.:0   1st Qu.:19.53  
    ##  Mode  :character   Median :0.000000   Median :0   Median :0   Median :21.03  
    ##                     Mean   :0.002303   Mean   :0   Mean   :0   Mean   :21.57  
    ##                     3rd Qu.:0.000000   3rd Qu.:0   3rd Qu.:0   3rd Qu.:22.91  
    ##                     Max.   :6.000000   Max.   :0   Max.   :0   Max.   :46.10  
    ##       ppwt           smoken           wtgain      
    ##  Min.   : 70.0   Min.   : 0.000   Min.   :-46.00  
    ##  1st Qu.:110.0   1st Qu.: 0.000   1st Qu.: 15.00  
    ##  Median :120.0   Median : 0.000   Median : 22.00  
    ##  Mean   :123.5   Mean   : 4.145   Mean   : 22.08  
    ##  3rd Qu.:134.0   3rd Qu.: 5.000   3rd Qu.: 28.00  
    ##  Max.   :287.0   Max.   :60.000   Max.   : 89.00

The birthweight data contains 4342 rows, 20 columns, and no missing
data.

The birthweight data contains variables such as `babysex` `bhead`
`blength` `delwt` `gaweeks` `mheight` `parity` `ppwt` `smoken` `fincome`
`mrace` `bwt` `frace` `malform` `menarche` `momage` `pnumlbw` `pnumgsa`
`ppbmi` `wtgain` . The data could be used to explore the effects of
several variables on a child’s birthweight.

#### Fit a model

fitting a model by using backward method. We want to find out the
predictors to put in our model.

``` r
model_crude=lm(bwt  ~ ., data = baby_df)%>% 
step(direction='backward') 
```

    ## Start:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     pnumlbw + pnumsga + ppbmi + ppwt + smoken + wtgain
    ## 
    ## 
    ## Step:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     pnumlbw + pnumsga + ppbmi + ppwt + smoken
    ## 
    ## 
    ## Step:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     pnumlbw + ppbmi + ppwt + smoken
    ## 
    ## 
    ## Step:  AIC=48717.83
    ## bwt ~ babysex + bhead + blength + delwt + fincome + frace + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     ppbmi + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - frace     4    124365 320848704 48712
    ## - malform   1      1419 320725757 48716
    ## - ppbmi     1      6346 320730684 48716
    ## - momage    1     28661 320752999 48716
    ## - mheight   1     66886 320791224 48717
    ## - menarche  1    111679 320836018 48717
    ## - ppwt      1    131132 320855470 48718
    ## <none>                  320724338 48718
    ## - fincome   1    193454 320917792 48718
    ## - parity    1    413584 321137922 48721
    ## - mrace     3    868321 321592659 48724
    ## - babysex   1    853796 321578134 48727
    ## - gaweeks   1   4611823 325336161 48778
    ## - smoken    1   5076393 325800732 48784
    ## - delwt     1   8008891 328733230 48823
    ## - blength   1 102050296 422774634 49915
    ## - bhead     1 106535716 427260054 49961
    ## 
    ## Step:  AIC=48711.51
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     malform + menarche + mheight + momage + mrace + parity + 
    ##     ppbmi + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - malform   1      1447 320850151 48710
    ## - ppbmi     1      6975 320855679 48710
    ## - momage    1     28379 320877083 48710
    ## - mheight   1     69502 320918206 48710
    ## - menarche  1    115708 320964411 48711
    ## - ppwt      1    133961 320982665 48711
    ## <none>                  320848704 48712
    ## - fincome   1    194405 321043108 48712
    ## - parity    1    414687 321263390 48715
    ## - babysex   1    852133 321700837 48721
    ## - gaweeks   1   4625208 325473911 48772
    ## - smoken    1   5036389 325885093 48777
    ## - delwt     1   8013099 328861802 48817
    ## - mrace     3  13540415 334389119 48885
    ## - blength   1 101995688 422844392 49908
    ## - bhead     1 106662962 427511666 49956
    ## 
    ## Step:  AIC=48709.53
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     menarche + mheight + momage + mrace + parity + ppbmi + ppwt + 
    ##     smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - ppbmi     1      6928 320857079 48708
    ## - momage    1     28660 320878811 48708
    ## - mheight   1     69320 320919470 48708
    ## - menarche  1    116027 320966177 48709
    ## - ppwt      1    133894 320984044 48709
    ## <none>                  320850151 48710
    ## - fincome   1    193784 321043934 48710
    ## - parity    1    414482 321264633 48713
    ## - babysex   1    851279 321701430 48719
    ## - gaweeks   1   4624003 325474154 48770
    ## - smoken    1   5035195 325885346 48775
    ## - delwt     1   8029079 328879230 48815
    ## - mrace     3  13553320 334403471 48883
    ## - blength   1 102009225 422859375 49906
    ## - bhead     1 106675331 427525481 49954
    ## 
    ## Step:  AIC=48707.63
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     menarche + mheight + momage + mrace + parity + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - momage    1     29211 320886290 48706
    ## - menarche  1    117635 320974714 48707
    ## <none>                  320857079 48708
    ## - fincome   1    195199 321052278 48708
    ## - parity    1    412984 321270064 48711
    ## - babysex   1    850020 321707099 48717
    ## - mheight   1   1078673 321935752 48720
    ## - ppwt      1   2934023 323791103 48745
    ## - gaweeks   1   4621504 325478583 48768
    ## - smoken    1   5039368 325896447 48773
    ## - delwt     1   8024939 328882018 48813
    ## - mrace     3  13551444 334408523 48881
    ## - blength   1 102018559 422875638 49904
    ## - bhead     1 106821342 427678421 49953
    ## 
    ## Step:  AIC=48706.02
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     menarche + mheight + mrace + parity + ppwt + smoken
    ## 
    ##            Df Sum of Sq       RSS   AIC
    ## - menarche  1    100121 320986412 48705
    ## <none>                  320886290 48706
    ## - fincome   1    240800 321127090 48707
    ## - parity    1    431433 321317724 48710
    ## - babysex   1    841278 321727568 48715
    ## - mheight   1   1076739 321963029 48719
    ## - ppwt      1   2913653 323799943 48743
    ## - gaweeks   1   4676469 325562760 48767
    ## - smoken    1   5045104 325931394 48772
    ## - delwt     1   8000672 328886962 48811
    ## - mrace     3  14667730 335554021 48894
    ## - blength   1 101990556 422876847 49902
    ## - bhead     1 106864308 427750598 49952
    ## 
    ## Step:  AIC=48705.38
    ## bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + 
    ##     mheight + mrace + parity + ppwt + smoken
    ## 
    ##           Df Sum of Sq       RSS   AIC
    ## <none>                 320986412 48705
    ## - fincome  1    245637 321232048 48707
    ## - parity   1    422770 321409181 48709
    ## - babysex  1    846134 321832545 48715
    ## - mheight  1   1012240 321998651 48717
    ## - ppwt     1   2907049 323893461 48743
    ## - gaweeks  1   4662501 325648912 48766
    ## - smoken   1   5073849 326060260 48771
    ## - delwt    1   8137459 329123871 48812
    ## - mrace    3  14683609 335670021 48894
    ## - blength  1 102191779 423178191 49903
    ## - bhead    1 106779754 427766166 49950

``` r
summary(model_crude)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ babysex + bhead + blength + delwt + fincome + 
    ##     gaweeks + mheight + mrace + parity + ppwt + smoken, data = baby_df)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1097.18  -185.52    -3.39   174.14  2353.44 
    ## 
    ## Coefficients:
    ##                     Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)       -6145.1507   141.9496 -43.291  < 2e-16 ***
    ## babysexmale         -28.5580     8.4549  -3.378 0.000737 ***
    ## bhead               130.7770     3.4466  37.944  < 2e-16 ***
    ## blength              74.9471     2.0190  37.120  < 2e-16 ***
    ## delwt                 4.1067     0.3921  10.475  < 2e-16 ***
    ## fincome               0.3180     0.1747   1.820 0.068844 .  
    ## gaweeks              11.5925     1.4621   7.929 2.79e-15 ***
    ## mheight               6.5940     1.7849   3.694 0.000223 ***
    ## mraceblack          -63.9057    42.3663  -1.508 0.131523    
    ## mracePuerto Rican   -25.7914    45.3502  -0.569 0.569578    
    ## mracewhite           74.8868    42.3146   1.770 0.076837 .  
    ## parity               96.3047    40.3362   2.388 0.017004 *  
    ## ppwt                 -2.6756     0.4274  -6.261 4.20e-10 ***
    ## smoken               -4.8434     0.5856  -8.271  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 272.3 on 4328 degrees of freedom
    ## Multiple R-squared:  0.7181, Adjusted R-squared:  0.7173 
    ## F-statistic: 848.1 on 13 and 4328 DF,  p-value: < 2.2e-16

From the output, we could see that some of the p-values for predictors
are less than 0.05, such as the `babysex` `bhead` `blength` `delwt`
`gaweeks` `mheight` `parity` `ppwt` `smoken` , we should include then in
the model.Also, for some predictors such as such as `fincome` and
`mrace`, the p-values are slightly greater than 0.05. Therefore, in
terms of predictor selection, we could also select them into our model.
Therefore, the pridictors that we put in our model are:`babysex` `bhead`
`blength` `delwt` `fincome` `gaweeks` `mheight` `mrace` `parity` `ppwt`
`smoken`

#### Fit the model with these variables:

``` r
model_fit = lm(bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + mheight + mrace + parity + ppwt + smoken, data = baby_df) 
```

#### Plot of model residuals against fitted values

``` r
  baby_df %>% 
  add_residuals(model_fit) %>% 
  add_predictions(model_fit) %>% 
  ggplot(aes(x = pred, y = resid)) +
  geom_point(alpha = 0.5) + labs( title = "Residuals against Fitted Values", x = "Fitted Value", y = "Residuals")
```

<img src="p8105_hw6_qx2199_files/figure-gfm/unnamed-chunk-8-1.png" width="90%" />

From the residual plot, we could see that the distribution for most of
the residuals are not heavily skewed, the center for most of the
residuals are around 0, especially when the predicted value is higher
than 2000. However, when the predicted values are smaller than 2000,
there are outliers–as the predicted value decrease, residuals increase.

#### Compare your model to two others:

One using length at birth and gestational age as predictors (main
effects only)–model main One using head circumference, length, sex, and
all interactions (including the three-way interaction) between
these–model inter

``` r
#cross validation
cross_validation = 
  crossv_mc(baby_df, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)) %>% 
  mutate(
    model_one = map(train, ~lm(bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + mheight + mrace + parity + ppwt + smoken, data = .x)),
    model_main = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    model_inter = map(train, ~lm(bwt ~ bhead * blength * babysex, data = .x))) %>% 
  mutate(
    rmse_one = map2_dbl(model_one, test, ~rmse(model = .x, data = .y)),
    rmse_main = map2_dbl(model_main, test, ~rmse(model = .x, data = .y)),
    rmse_inter = map2_dbl(model_inter, test, ~rmse(model = .x, data = .y)),
  )
# plot for RMSE
rmse_plot = 
  cross_validation  %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_"
  ) %>% 
  ggplot(aes(x = model, y = rmse, fill = model)) +
  geom_violin(alpha = 0.5) +
  labs( title = "Cross Validation Comparisons", x = "Model", y = "RMSE")
   
rmse_plot
```

<img src="p8105_hw6_qx2199_files/figure-gfm/unnamed-chunk-9-1.png" width="90%" />

According to the plot,my model (model\_one, with preictors: `babysex`
`bhead` `blength` `delwt` `fincome` `gaweeks` `mheight` `mrace` `parity`
`ppwt` `smoken` ) has the lowest RMSE. Therefore, it’s the best model
among the three models.The model with only main effects ( `blength`
`gaweeks` ) has the highest RMSE and hence is the worst one.The model
with length, sex, and all interactions has the medium RMSE among the
three models. Therefore, it’s the second best model.

### Problem 3

load the data

``` r
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

    ## Registered S3 method overwritten by 'hoardr':
    ##   method           from
    ##   print.cache_info httr

    ## using cached file: /Users/hellotutu/Library/Caches/R/noaa_ghcnd/USW00094728.dly

    ## date created (size, mb): 2020-10-19 00:37:11 (7.525)

    ## file min/max dates: 1869-01-01 / 2020-10-31

Use 5000 bootstrap samples and, for each bootstrap sample, produce
estimates of these two quantities.

``` r
set.seed(1)
weather_new = 
weather_df %>% 
modelr::bootstrap(n = 5000) %>% 
mutate(
  models = map(.x = strap, ~ lm(tmax ~ tmin, data = .x)),
  r_glance = map(models, broom::glance),
  beta = map(models, broom::tidy),
  )

weather_final=
  weather_new %>%  
  unnest(r_glance,beta) %>%  
  select(.id, term, estimate, r.squared) %>% 
  pivot_wider( names_from = term,values_from = estimate) %>% 
  janitor::clean_names() %>% 
  mutate(log_one_zero = log(intercept*tmin))
```

Plot the distribution of your estimates, and describe these in words.

#### Plot the distribution for r-square

``` r
 weather_final %>% 
  ggplot(aes(x = r_squared)) + 
  geom_density()
```

<img src="p8105_hw6_qx2199_files/figure-gfm/unnamed-chunk-12-1.png" width="90%" />
For the r squared distribution plot, it’s little-bit left-skewed with
peak that around 0.913.

#### Plot the distribution for log(beta0 \*beta1)

``` r
 weather_final %>% 
  ggplot(aes(x = log_one_zero)) + 
  geom_density()
```

<img src="p8105_hw6_qx2199_files/figure-gfm/unnamed-chunk-13-1.png" width="90%" />
The log(beta0 \*beta1) is approximately normal-distributed, with peak
that around 2.012

#### 95% confidence interval for r-square

``` r
r_ci = 
  weather_final %>% 
  summarize(
   r_ci_lower = quantile(r_squared, 0.025),
   r_ci_upper = quantile(r_squared, 0.975)
  ) %>% 
  knitr::kable(digits = 3)
r_ci
```

| r\_ci\_lower | r\_ci\_upper |
| -----------: | -----------: |
|        0.894 |        0.927 |

95%CI for r-square is (0.894, 0.927)

#### 95% confidence interval for log(beta0 \* beta1)

``` r
log_ci = 
  weather_final %>% 
  summarize(
   log_ci_lower = quantile(log_one_zero, 0.025),
   log_ci_upper = quantile(log_one_zero, 0.975)
  ) %>% 
  knitr::kable(digits =3)
log_ci
```

| log\_ci\_lower | log\_ci\_upper |
| -------------: | -------------: |
|          1.965 |          2.059 |

95%CI for log(beta0 \* beta1) is (1.965, 2.059)
